FROM jboss/wildfly

LABEL maintainer="Victor Antunes <victor.antunes.ignacio@gmail.com>"

ADD target/department-store-1.0-SNAPSHOT.war /opt/jboss/wildfly/standalone/deployments/

RUN /opt/jboss/wildfly/bin/add-user.sh admin Admin#70365 --silent